import { NextResponse, type NextRequest } from "next/server";

import { defaultLocale, locales } from "@/lib/i18n/config";

// Default-locale rewrite. Chinese (`zh-TW`) is served at the un-prefixed URL
// (`/announcement`), English lives under `/en/*`. This is the ONLY middleware
// in the app and is deliberately minimal: no cookies, no `Accept-Language`
// detection — purely structural, so static output stays CDN-cacheable and the
// cookieless/ISR guarantees hold. `next.config` `redirects` run before this,
// so the legacy/edit redirects still compose.

// Root-level route handlers served OUTSIDE the [locale] segment.
const ROOT_ROUTE_PREFIXES = ["/api", "/auth"];
// Root-level metadata routes (generated by app/sitemap.ts + app/robots.ts).
const ROOT_METADATA = new Set(["/sitemap.xml", "/robots.txt"]);
// Public static assets (og.png, favicon.ico, fonts, …). `.xml` is intentionally
// excluded so route handlers like /announcement/rss.xml get rewritten.
const STATIC_FILE = /\.(?:png|jpe?g|gif|svg|ico|webp|avif|txt|woff2?|ttf|otf|css|js|map|json|pdf)$/i;

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Already carries a non-default locale prefix (`/en`, `/en/...`) → serve as-is.
  const hasLocalePrefix = locales.some(
    (l) => l !== defaultLocale && (pathname === `/${l}` || pathname.startsWith(`/${l}/`))
  );
  if (hasLocalePrefix) return NextResponse.next();

  // Root-level routes / metadata / static assets are not under [locale].
  if (
    ROOT_METADATA.has(pathname) ||
    ROOT_ROUTE_PREFIXES.some((p) => pathname === p || pathname.startsWith(`${p}/`)) ||
    STATIC_FILE.test(pathname)
  ) {
    return NextResponse.next();
  }

  // Bare path → serve the default-locale tree; the visible URL stays bare.
  const url = request.nextUrl.clone();
  url.pathname = `/${defaultLocale}${pathname === "/" ? "" : pathname}`;
  return NextResponse.rewrite(url);
}

export const config = {
  // Run on everything except Next internals; static-file/route passthrough is
  // handled in the body above.
  matcher: ["/((?!_next/).*)"],
};
