import { unstable_cache } from "next/cache";
import { createPublicClient } from "@/lib/supabase/public";
import { isUuid } from "@/lib/slug";
import { livePublishAtFilter } from "@/lib/scheduling";
import type { Announcement } from "@winlab/db";

// Only fetches published + global (event_id IS NULL). Admin-only drafts are
// merged in on the client via useAuth so this cache stays visitor-safe.
//
// Every query below also ANDs in `livePublishAtFilter()` on top of
// `.eq("status", "published")` — belt-and-suspenders for scheduled
// publishing (#47). The RLS policy on `announcements` enforces the same
// `publish_at` gate for anon/authenticated reads; this app-level filter
// exists so a cached-but-not-yet-live row can't leak through even before
// the next cron-triggered revalidation (see app/api/cron/publish-scheduled).
export const getPublishedAnnouncements = unstable_cache(
  async (): Promise<Announcement[]> => {
    const supabase = createPublicClient();
    const { data } = await supabase
      .from("announcements")
      .select("*")
      .eq("status", "published")
      .or(livePublishAtFilter())
      .is("event_id", null)
      .order("date", { ascending: false });
    return (data as Announcement[] | null) ?? [];
  },
  ["announcements-published"],
  { tags: ["announcements-published"], revalidate: 3600 },
);

// Home page wants only the 3 most recent; share the same cache tag so edits
// invalidate both variants at once.
export const getLatestAnnouncements = unstable_cache(
  async (): Promise<Announcement[]> => {
    const supabase = createPublicClient();
    const { data } = await supabase
      .from("announcements")
      .select("*")
      .eq("status", "published")
      .or(livePublishAtFilter())
      .is("event_id", null)
      .order("date", { ascending: false })
      .limit(3);
    return (data as Announcement[] | null) ?? [];
  },
  ["announcements-latest"],
  { tags: ["announcements-published"], revalidate: 3600 },
);

// Single published announcement by slug — the canonical lookup for the
// detail page + its generateMetadata now that URLs are slug-based. Drafts
// (and not-yet-live scheduled posts) return null here on purpose; admins
// reach them through `?mode=edit`.
export const getPublishedAnnouncementBySlug = unstable_cache(
  async (slug: string): Promise<Announcement | null> => {
    const supabase = createPublicClient();
    const { data } = await supabase
      .from("announcements")
      .select("*")
      .eq("slug", slug)
      .eq("status", "published")
      .or(livePublishAtFilter())
      .maybeSingle();
    return (data as Announcement | null) ?? null;
  },
  ["announcement-by-slug"],
  { tags: ["announcements-published"], revalidate: 3600 },
);

// Legacy lookup by id, only reached when a visitor follows a pre-slug
// `/announcement/[uuid]` link — the page 301s to the slug URL on a hit.
export const getPublishedAnnouncementById = unstable_cache(
  async (id: string): Promise<Announcement | null> => {
    const supabase = createPublicClient();
    const { data } = await supabase
      .from("announcements")
      .select("*")
      .eq("id", id)
      .eq("status", "published")
      .or(livePublishAtFilter())
      .maybeSingle();
    return (data as Announcement | null) ?? null;
  },
  ["announcement-by-id"],
  { tags: ["announcements-published"], revalidate: 3600 },
);

// `param` is whatever arrived in the `[id]` route segment — a slug for every
// link generated by this app, or a legacy UUID for old bookmarks/backlinks.
export async function getPublishedAnnouncementByParam(
  param: string,
): Promise<Announcement | null> {
  const bySlug = await getPublishedAnnouncementBySlug(param);
  if (bySlug) return bySlug;
  if (isUuid(param)) return getPublishedAnnouncementById(param);
  return null;
}

export async function getPublishedAnnouncementSlugs(): Promise<string[]> {
  const supabase = createPublicClient();
  const { data } = await supabase
    .from("announcements")
    .select("slug")
    .eq("status", "published")
    .is("event_id", null);
  return (data ?? []).map((row: { slug: string }) => row.slug);
}
